### ISSUE TITLE
Implement the oracle integration

### ISSUE THREAD

**Issue by brolag** [brolag/eusd#13]

**Comment by AzizRay** [comment]
I pushed the oracle-integration branch, which implements the Tellor Oracle integration into the EncodeStableCoinLogic contract. Afterward, I created a new branch, oracle-testing, based on oracle-integration, where I wrote tests for the integration.

**Comment by AzizRay** [comment]
I tried to build the contract on the main repo but had issues with importing libraries. So I had to modify the contract and deployment script and tested locally with TellorPlayground in a separate Foundry folder. Everything built successfully, and the tests passed, so the Tellor integration works locally. 🎉
The current integration in the main repo (UsingTellor) can only be confirmed by testing on a testnet/mainnet.
