### ISSUE TITLE
Build Vault Contract to Handle ETH Collateral

### ISSUE THREAD

**Issue by brolag** [brolag/eusd#3]
**Description**: Create a vault contract to handle user ETH deposits and withdrawals. The vault will store user collateral for minting eUSD.

 **Subtasks**:
  - Implement deposit and withdrawal functionality for ETH collateral.
  - Add mappings to track each user's ETH collateral balance.
  - Implement functions to check and retrieve collateral for each user.
  - Write unit tests to ensure proper functionality of deposits, withdrawals, and collateral tracking.

 **Acceptance Criteria**:
  - Users can deposit and withdraw ETH correctly.
  - Users' ETH balances are tracked accurately in the contract.
  - Unit tests for deposits, withdrawals, and balance retrieval pass.

**Comment by Amrit-ko** [comment]
@brolag I think we don't need extra vault contract. All collateral can be stored in core contract

**Comment by brolag** [comment]
I agree. Closing this for now.
